name: Pyinstaller

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  windows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@main
      with:
        path: app.py
    - uses: actions/upload-artifact@v2
      with:
        name: windows-build
        path: dist
  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Package Application
    uses: JackMcKew/pyinstaller-action-linux@main
    with:
        path: app.py
    - uses: actions/upload-artifact@v2
    with:
        name: linux-build
        path: dist
